CREATE TABLE IF NOT EXISTS organizations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    ticker VARCHAR(10) UNIQUE,
    industry VARCHAR(50),
    headquarters VARCHAR(100),
    website VARCHAR(100),
    employees INTEGER,
    ceo VARCHAR(100)
);

-- Fortune 500 Companies Insert Statements
INSERT INTO organizations (name, ticker, industry, headquarters, website, ceo, employees) VALUES
('Walmart', 'WMT', 'General Merchandisers', 'Bentonville, Arkansas', 'https://walmart.com', '2,100,000', 'Douglas Mcmillon'),
('Amazon', 'AMZN', 'Internet Services and Retailing', 'Seattle, Washington', 'https://amazon.com', '1,525,000', 'Andrew R. Jassy'),
('Apple', 'AAPL', 'Computers, Office Equipment', 'Cupertino, California', 'https://apple.com', '161,000', 'Timothy D. Cook'),
('UnitedHealth Group', 'UNH', 'Health Care: Insurance and Managed Care', 'Minnetonka, Minnesota', 'https://unitedhealthgroup.com', '440,000', 'Andrew P. Witty'),
('Berkshire Hathaway', 'BRKA', 'Insurance: Property and Casualty (Stock)', 'Omaha, Nebraska', 'https://berkshirehathaway.com', '396,500', 'Warren E. Buffett'),
('CVS Health', 'CVS', 'Health Care: Pharmacy and Other Services', 'Woonsocket, Rhode Island', 'https://cvshealth.com', '259,500', 'Karen S. Lynch'),
('Exxon Mobil', 'XOM', 'Petroleum Refining', 'Spring, Texas', 'https://exxonmobil.com', '61,500', 'Darren W. Woods'),
('Alphabet', 'GOOGL', 'Internet Services and Retailing', 'Mountain View, California', 'https://abc.xyz', '182,502', 'Sundar Pichai'),
('McKesson', 'MCK', 'Wholesalers: Health Care', 'Irving, Texas', 'https://mckesson.com', '48,000', 'Brian S. Tyler'),
('Cencora', 'COR', 'Wholesalers: Health Care', 'Conshohocken, Pennsylvania', 'https://cencora.com', '44,000', 'Steven H. Collis'),
('Costco', 'COST', 'General Merchandisers', 'Issaquah, Washington', 'https://costco.com', '316,000', 'Ron M. Vachris'),
('JPMorgan Chase', 'JPM', 'Commercial Banks', 'New York, New York', 'https://jpmorganchase.com', '309,926', 'Jamie Dimon'),
('Microsoft', 'MSFT', 'Computer Software', 'Redmond, Washington', 'https://microsoft.com', '221,000', 'Satya Nadella'),
('Cardinal Health', 'CAH', 'Wholesalers: Health Care', 'Dublin, Ohio', 'https://cardinalhealth.com', '47,520', 'Jason M. Hollar'),
('Chevron', 'CVX', 'Petroleum Refining', 'San Ramon, California', 'https://chevron.com', '45,600', 'Michael K. Wirth'),
('Cigna Group', 'CI', 'Health Care: Pharmacy and Other Services', 'Bloomfield, Connecticut', 'https://thecignagroup.com', '71,413', 'David M. Cordani'),
('Ford Motor', 'F', 'Motor Vehicles & Parts', 'Dearborn, Michigan', 'https://ford.com', '177,000', 'Jim Farley'),
('Bank of America', 'BAC', 'Commercial Banks', 'Charlotte, North Carolina', 'https://bankofamerica.com', '212,985', 'Brian T. Moynihan'),
('General Motors', 'GM', 'Motor Vehicles & Parts', 'Detroit, Michigan', 'https://gm.com', '163,000', 'Mary T. Barra'),
('Elevance Health', 'ELV', 'Health Care: Insurance and Managed Care', 'Indianapolis, Indiana', 'https://elevancehealth.com', '104,900', 'Gail K. Boudreaux'),
('Citigroup', 'C', 'Commercial Banks', 'New York, New York', 'https://citigroup.com', '237,925', 'Jane Fraser'),
('Centene', 'CNC', 'Health Care: Insurance and Managed Care', 'St. Louis, Missouri', 'https://centene.com', '67,700', 'Sarah M. London'),
('Home Depot', 'HD', 'Specialty Retailers: Other', 'Atlanta, Georgia', 'https://homedepot.com', '463,100', 'Edward P. Decker'),
('Marathon Petroleum', 'MPC', 'Petroleum Refining', 'Findlay, Ohio', 'https://marathonpetroleum.com', '18,200', 'Michael J. Hennigan'),
('Kroger', 'KR', 'Food & Drug Stores', 'Cincinnati, Ohio', 'https://thekrogerco.com', '414,000', 'Rodney Mcmullen'),
('Phillips 66', 'PSX', 'Petroleum Refining', 'Houston, Texas', 'https://phillips66.com', '14,000', 'Mark Lashier'),
('Fannie Mae', 'FNMA', 'Diversified Financials', 'Washington, District Of Columbia', 'https://fanniemae.com', '8,100', 'Priscilla Almodovar'),
('Walgreens Boots Alliance', 'WBA', 'Food & Drug Stores', 'Deerfield, Illinois', 'https://walgreensbootsalliance.com', '268,500', 'Timothy Wentworth'),
('Valero Energy', 'VLO', 'Petroleum Refining', 'San Antonio, Texas', 'https://valero.com', '9,897', 'R. Lane Riggs'),
('Meta Platforms', 'META', 'Internet Services and Retailing', 'Menlo Park, California', 'https://fb.com', '67,317', 'Mark Zuckerberg'),
('Verizon Communications', 'VZ', 'Telecommunications', 'New York, New York', 'https://verizon.com', '105,400', 'Hans E. Vestberg'),
('AT&T', 'T', 'Telecommunications', 'Dallas, Texas', 'https://att.com', '150,470', 'John T. Stankey'),
('Comcast', 'CMCSA', 'Telecommunications', 'Philadelphia, Pennsylvania', 'https://comcastcorporation.com', '186,000', 'Brian L. Roberts'),
('Wells Fargo', 'WFC', 'Commercial Banks', 'San Francisco, California', 'https://wellsfargo.com', '226,000', 'Charles W. Scharf'),
('Goldman Sachs Group', 'GS', 'Commercial Banks', 'New York, New York', 'https://goldmansachs.com', '45,300', 'David M. Solomon'),
('Freddie Mac', 'FMCC', 'Diversified Financials', 'McLean, Virginia', 'https://freddiemac.com', '8,020', 'Michael T. Hutchins'),
('Target', 'TGT', 'General Merchandisers', 'Minneapolis, Minnesota', 'https://target.com', '415,000', 'Brian C. Cornell'),
('Humana', 'HUM', 'Health Care: Insurance and Managed Care', 'Louisville, Kentucky', 'https://humana.com', '67,600', 'Bruce D. Broussard'),
('Tesla', 'TSLA', 'Motor Vehicles & Parts', 'Austin, Texas', 'https://tesla.com', '140,473', 'Elon Musk'),
('Morgan Stanley', 'MS', 'Commercial Banks', 'New York, New York', 'https://morganstanley.com', '80,006', 'Edward N. Pick'),
('Johnson & Johnson', 'JNJ', 'Pharmaceuticals', 'New Brunswick, New Jersey', 'https://jnj.com', '131,900', 'Joaquin Duato'),
('Archer Daniels Midland', 'ADM', 'Food Production', 'Chicago, Illinois', 'https://adm.com', '41,008', 'Juan R. Luciano'),
('PepsiCo', 'PEP', 'Food Consumer Products', 'Purchase, New York', 'https://pepsico.com', '318,000', 'Ramon L. Laguarta'),
('United Parcel Service', 'UPS', 'Mail, Package and Freight Delivery', 'Atlanta, Georgia', 'https://ups.com', '382,550', 'Carol B. Tome'),
('FedEx', 'FDX', 'Mail, Package and Freight Delivery', 'Memphis, Tennessee', 'https://fedex.com', '446,400', 'Rajesh Subramaniam'),
('Walt Disney', 'DIS', 'Entertainment', 'Burbank, California', 'https://thewaltdisneycompany.com', '199,125', 'Robert A. Chapek'),
('Dell Technologies', 'DELL', 'Computers, Office Equipment', 'Round Rock, Texas', 'https://delltechnologies.com', '120,000', 'Michael S. Dell'),
('Lowe''s', 'LOW', 'Specialty Retailers: Other', 'Mooresville, North Carolina', 'https://lowes.com', '226,000', 'Marvin R. Ellison'),
('Procter & Gamble', 'PG', 'Household and Personal Products', 'Cincinnati, Ohio', 'https://pginvestor.com', '107,000', 'Jon R. Moeller'),
('Energy Transfer', 'ET', 'Pipelines', 'Dallas, Texas', 'https://energytransfer.com', '13,786', 'Thomas E. Long'),
('Boeing', 'BA', 'Aerospace & Defense', 'Arlington, Virginia', 'https://boeing.com', '171,000', 'David L. Calhoun'),
('Albertsons', 'ACI', 'Food & Drug Stores', 'Boise, Idaho', 'https://albertsonscompanies.com', '198,650', 'Vivek Sankaran'),
('Sysco', 'SYY', 'Wholesalers: Food and Grocery', 'Houston, Texas', 'https://sysco.com', '71,750', 'Kevin P. Hourican'),
('RTX', 'RTX', 'Aerospace & Defense', 'Arlington, Virginia', 'https://rtx.com', '185,000', 'Christopher T. Calio'),
('General Electric', 'GE', 'Industrial Machinery', 'Boston, Massachusetts', 'https://ge.com', '125,000', 'Lawrence Culp'),
('Lockheed Martin', 'LMT', 'Aerospace & Defense', 'Bethesda, Maryland', 'https://lockheedmartin.com', '122,000', 'James D. Taiclet Jr.'),
('American Express', 'AXP', 'Diversified Financials', 'New York, New York', 'https://americanexpress.com', '74,600', 'Stephen J. Squeri'),
('Caterpillar', 'CAT', 'Construction and Farm Machinery', 'Irving, Texas', 'https://caterpillar.com', '113,200', 'James Umpleby'),
('MetLife', 'MET', 'Insurance: Life, Health (Stock)', 'New York, New York', 'https://metlife.com', '45,000', 'Michel A. Khalaf'),
('HCA Healthcare', 'HCA', 'Health Care: Medical Facilities', 'Nashville, Tennessee', 'https://hcahealthcare.com', '265,000', 'Samuel N. Hazen'),
('Progressive', 'PGR', 'Insurance: Property and Casualty (Stock)', 'Mayfield Village, Ohio', 'https://progressive.com', '61,432', 'Susan Patricia Griffith'),
('International Business Machines', 'IBM', 'Information Technology Services', 'Armonk, New York', 'https://ibm.com', '296,600', 'Arvind Krishna'),
('Deere', 'DE', 'Construction and Farm Machinery', 'Moline, Illinois', 'https://deere.com', '82,956', 'John C. May'),
('Nvidia', 'NVDA', 'Semiconductors and Other Electronic Components', 'Santa Clara, California', 'https://nvidia.com', '29,600', 'Jen-Hsun Huang'),
('StoneX Group', 'SNEX', 'Diversified Financials', 'New York, New York', 'https://stonex.com', '4,137', 'Sean M. O''Connor'),
('Merck', 'MRK', 'Pharmaceuticals', 'Rahway, New Jersey', 'https://merck.com', '71,000', 'Robert M. Davis'),
('ConocoPhillips', 'COP', 'Mining, Crude-Oil Production', 'Houston, Texas', 'https://conocophillips.com', '9,900', 'Ryan M. Lance'),
('Pfizer', 'PFE', 'Pharmaceuticals', 'New York, New York', 'https://pfizer.com', '88,000', 'Albert Bourla'),
('Delta Air Lines', 'DAL', 'Airlines', 'Atlanta, Georgia', 'https://delta.com', '103,000', 'Edward H. Bastian'),
('TD Synnex', 'SNX', 'Wholesalers: Electronics and Office Equipment', 'Fremont, California', 'https://tdsynnex.com', '28,000', 'Richard T. Hume'),
('Allstate', 'ALL', 'Insurance: Property and Casualty (Stock)', 'Northbrook, Illinois', 'https://allstate.com', '53,200', 'Thomas J. Wilson'),
('Cisco Systems', 'CSCO', 'Network and Other Communications Equipment', 'San Jose, California', 'https://cisco.com', '84,900', 'Charles H. Robbins'),
('Charter Communications', 'CHTR', 'Telecommunications', 'Stamford, Connecticut', 'https://charter.com', '101,100', 'Christopher L. Winfrey'),
('AbbVie', 'ABBV', 'Pharmaceuticals', 'North Chicago, Illinois', 'https://abbvie.com', '50,000', 'Richard A. Gonzalez'),
('Intel', 'INTC', 'Semiconductors and Other Electronic Components', 'Santa Clara, California', 'https://intel.com', '124,800', 'Patrick P. Gelsinger'),
('TJX', 'TJX', 'Specialty Retailers: Apparel', 'Framingham, Massachusetts', 'https://tjx.com', '349,000', 'Ernie L. Herrman'),
('Prudential Financial', 'PRU', 'Insurance: Life, Health (Stock)', 'Newark, New Jersey', 'https://prudential.com', '40,366', 'Charles F. Lowrey'),
('HP', 'HPQ', 'Computers, Office Equipment', 'Palo Alto, California', 'https://hp.com', '58,000', 'Enrique J. Lores'),
('United Airlines Holdings', 'UAL', 'Airlines', 'Chicago, Illinois', 'https://united.com', '103,300', 'Scott Kirby'),
('Performance Food Group', 'PFGC', 'Wholesalers: Food and Grocery', 'Richmond, Virginia', 'https://pfgc.com', '34,825', 'George L. Holm'),
('Tyson Foods', 'TSN', 'Food Production', 'Springdale, Arkansas', 'https://tysonfoods.com', '139,000', 'Donnie D. King'),
('American Airlines Group', 'AAL', 'Airlines', 'Fort Worth, Texas', 'https://aa.com', '132,100', 'Robert D. Isom'),
('Nike', 'NKE', 'Apparel', 'Beaverton, Oregon', 'https://investors.nike.com', '83,700', 'John Donahoe'),
('Oracle', 'ORCL', 'Computer Software', 'Austin, Texas', 'https://oracle.com', '164,000', 'Safra A. Catz'),
('Enterprise Products Partners', 'EPD', 'Pipelines', 'Houston, Texas', 'https://enterpriseproducts.com', '7,500', 'James Teague'),
('Capital One Financial', 'COF', 'Commercial Banks', 'McLean, Virginia', 'https://capitalone.com', '51,987', 'Richard D. Fairbank'),
('Plains GP Holdings', 'PAGP', 'Pipelines', 'Houston, Texas', 'https://plains.com', '4,200', 'Wilfred C.W. Chiang'),
('World Kinect', 'WKC', 'Energy', 'Miami, Florida', 'https://world-kinect.com', '5,289', 'Michael J. Kasbar'),
('American International Group', 'AIG', 'Insurance: Property and Casualty (Stock)', 'New York, New York', 'https://aig.com', '25,200', 'Peter S. Zaffino'),
('Coca-Cola', 'KO', 'Beverages', 'Atlanta, Georgia', 'https://coca-colacompany.com', '79,100', 'James R. Quincey'),
('Bristol-Myers Squibb', 'BMY', 'Pharmaceuticals', 'Princeton, New Jersey', 'https://bms.com', '34,100', 'Christopher S. Boerner'),
('Dow', 'DOW', 'Chemicals', 'Midland, Michigan', 'https://dow.com', '35,900', 'James R. Fitterling'),
('Best Buy', 'BBY', 'Specialty Retailers: Other', 'Richfield, Minnesota', 'https://investors.bestbuy.com', '85,000', 'Corie S. Barry'),
('Thermo Fisher Scientific', 'TMO', 'Scientific, Photographic and Control Equipment', 'Waltham, Massachusetts', 'https://thermofisher.com', '122,000', 'Marc N. Casper'),
('General Dynamics', 'GD', 'Aerospace & Defense', 'Reston, Virginia', 'https://gd.com', '111,600', 'Phebe N. Novakovic'),
('Travelers', 'TRV', 'Insurance: Property and Casualty (Stock)', 'New York, New York', 'https://travelers.com', '33,133', 'Alan Schnitzer'),
('Warner Bros. Discovery', 'WBD', 'Entertainment', 'New York, New York', 'https://wbd.com', '35,300', 'David M. Zaslav'),
('U.S. Bancorp', 'USB', 'Commercial Banks', 'Minneapolis, Minnesota', 'https://usbank.com', '75,465', 'Andrew J. Cecere'),
('Abbott Laboratories', 'ABT', 'Medical Products and Equipment', 'Abbott Park, Illinois', 'https://abbott.com', '114,000', 'Robert B. Ford'),
('Northrop Grumman', 'NOC', 'Aerospace & Defense', 'Falls Church, Virginia', 'https://northropgrumman.com', '101,000', 'Kathy Warden'),
('Dollar General', 'DG', 'Specialty Retailers: Other', 'Goodlettsville, Tennessee', 'https://dollargeneral.com', '185,800', 'Todd J. Vasos'),
('PBF Energy', 'PBF', 'Petroleum Refining', 'Parsippany, New Jersey', 'https://pbfenergy.com', '3,776', 'Matthew C. Lucey'),
('Uber Technologies', 'UBER', 'Internet Services and Retailing', 'San Francisco, California', 'https://uber.com', '30,400', 'Dara Khosrowshahi'),
('Honeywell International', 'HON', 'Industrial Machinery', 'Charlotte, North Carolina', 'https://honeywell.com', '95,000', 'Vimal Kapur'),
('Mondelez International', 'MDLZ', 'Food Consumer Products', 'Chicago, Illinois', 'https://mondelezinternational.com', '91,000', 'Dirk Van De Put'),
('Starbucks', 'SBUX', 'Food Services', 'Seattle, Washington', 'https://starbucks.com', '381,000', 'Laxman Narasimhan'),
('Qualcomm', 'QCOM', 'Semiconductors and Other Electronic Components', 'San Diego, California', 'https://qualcomm.com', '50,000', 'Cristiano R. Amon'),
('Broadcom', 'AVGO', 'Semiconductors and Other Electronic Components', 'Palo Alto, California', 'https://broadcom.com', '20,000', 'Hock E. Tan'),
('US Foods Holding', 'USFD', 'Wholesalers: Food and Grocery', 'Rosemont, Illinois', 'https://usfoods.com', '30,000', 'David Flitman'),
('D.R. Horton', 'DHI', 'Homebuilders', 'Arlington, Texas', 'https://drhorton.com', '13,450', 'Paul J. Romanowski'),
('Philip Morris International', 'PM', 'Tobacco', 'Stamford, Connecticut', 'https://pmi.com', '82,700', 'Jacek Olczak'),
('Paccar', 'PCAR', 'Motor Vehicles & Parts', 'Bellevue, Washington', 'https://paccar.com', '32,400', 'Preston Feight'),
('Salesforce', 'CRM', 'Computer Software', 'San Francisco, California', 'https://salesforce.com', '72,682', 'Marc R. Benioff'),
('Nucor', 'NUE', 'Metals', 'Charlotte, North Carolina', 'https://nucor.com', '32,000', 'Leon J. Topalian'),
('Jabil', 'JBL', 'Semiconductors and Other Electronic Components', 'St. Petersburg, Florida', 'https://jabil.com', '236,000', 'Kenneth S. Wilson'),
('Lennar', 'LEN', 'Homebuilders', 'Miami, Florida', 'https://lennar.com', '12,284', 'Jonathan M. Jaffe'),
('Eli Lilly', 'LLY', 'Pharmaceuticals', 'Indianapolis, Indiana', 'https://lilly.com', '43,000', 'David A. Ricks'),
('Molina Healthcare', 'MOH', 'Health Care: Insurance and Managed Care', 'Long Beach, California', 'https://molinahealthcare.com', '18,000', 'Joseph M. Zubretsky'),
('Cummins', 'CMI', 'Industrial Machinery', 'Columbus, Indiana', 'https://cummins.com', '75,500', 'Jennifer Rumsey'),
('Bank of New York Mellon', 'BK', 'Commercial Banks', 'New York, New York', 'https://bnymellon.com', '53,400', 'Robin Vince'),
('Netflix', 'NFLX', 'Entertainment', 'Los Gatos, California', 'https://netflix.com', '13,000', 'Ted Sarandos'),
('Truist Financial', 'TFC', 'Commercial Banks', 'Charlotte, North Carolina', 'https://truist.com', '49,935', 'William H. Rogers Jr.'),
('Arrow Electronics', 'ARW', 'Wholesalers: Electronics and Office Equipment', 'Centennial, Colorado', 'https://arrow.com', '22,100', 'Sean J. Kerins'),
('3M', 'MMM', 'Chemicals', 'St. Paul, Minnesota', 'https://3m.com', '85,000', 'William M. Brown'),
('Visa', 'V', 'Financial Data Services', 'San Francisco, California', 'https://visa.com', '28,800', 'Ryan Mcinerney'),
('Apollo Global Management', 'APO', 'Securities', 'New York, New York', 'https://apollo.com', '6,855', 'Marc Rowan'),
('HF Sinclair', 'DINO', 'Petroleum Refining', 'Dallas, Texas', 'https://hfsinclair.com', '5,218', 'Tim Go'),
('CBRE Group', 'CBRE', 'Real Estate', 'Dallas, Texas', 'https://cbre.com', '130,000', 'Robert E. Sulentic'),
('PNC Financial Services Group', 'PNC', 'Commercial Banks', 'Pittsburgh, Pennsylvania', 'https://pnc.com', '55,612', 'William S. Demchak'),
('Lithia Motors', 'LAD', 'Automotive Retailing, Services', 'Medford, Oregon', 'https://investors.lithiadriveway.com', '25,051', 'Bryan B. Deboer'),
('CarMax', 'KMX', 'Automotive Retailing, Services', 'Richmond, Virginia', 'https://carmax.com', '30,621', 'William D. Nash'),
('Paramount Global', 'PARA', 'Entertainment', 'New York, New York', 'https://paramount.com', '24,150', 'Robert M. Bakish'),
('Dollar Tree', 'DLTR', 'Specialty Retailers: Other', 'Chesapeake, Virginia', 'https://dollartree.com', '138,860', 'Richard W. Dreiling'),
('United Natural Foods', 'UNFI', 'Wholesalers: Food and Grocery', 'Providence, Rhode Island', 'https://unfi.com', '29,455', 'Sandy Douglas'),
('PayPal Holdings', 'PYPL', 'Financial Data Services', 'San Jose, California', 'https://paypal.com', '27,200', 'Alex Chriss'),
('Penske Automotive Group', 'PAG', 'Automotive Retailing, Services', 'Bloomfield Hills, Michigan', 'https://penskeautomotive.com', '28,000', 'Roger S. Penske'),
('Hewlett Packard Enterprise', 'HPE', 'Computers, Office Equipment', 'Spring, Texas', 'https://hpe.com', '62,000', 'Antonio F. Neri'),
('Duke Energy', 'DUK', 'Utilities: Gas and Electric', 'Charlotte, North Carolina', 'https://duke-energy.com', '27,037', 'Lynn J. Good'),
('Occidental Petroleum', 'OXY', 'Mining, Crude-Oil Production', 'Houston, Texas', 'https://oxy.com', '12,570', 'Vicki Hollub'),
('NRG Energy', 'NRG', 'Energy', 'Houston, Texas', 'https://nrg.com', '18,131', 'Lawrence S. Coben'),
('Amgen', 'AMGN', 'Pharmaceuticals', 'Thousand Oaks, California', 'https://amgen.com', '26,700', 'Robert A. Bradway'),
('NextEra Energy', 'NEE', 'Utilities: Gas and Electric', 'Juno Beach, Florida', 'https://nexteraenergy.com', '16,800', 'John W. Ketchum'),
('Danaher', 'DHR', 'Medical Products and Equipment', 'Washington, District Of Columbia', 'https://danaher.com', '62,000', 'Rainer M. Blair'),
('Gilead Sciences', 'GILD', 'Pharmaceuticals', 'Foster City, California', 'https://gilead.com', '18,000', 'Daniel P. O''Day'),
('AutoNation', 'AN', 'Automotive Retailing, Services', 'Fort Lauderdale, Florida', 'https://autonation.com', '25,300', 'Michael M. Manley'),
('Kraft Heinz', 'KHC', 'Food Consumer Products', 'Chicago, Illinois', 'https://kraftheinzcompany.com', '36,000', 'Carlos Abrams-Rivera'),
('Avnet', 'AVT', 'Wholesalers: Electronics and Office Equipment', 'Phoenix, Arizona', 'https://avnet.com', '15,800', 'Philip R. Gallagher'),
('Applied Materials', 'AMAT', 'Semiconductors and Other Electronic Components', 'Santa Clara, California', 'https://appliedmaterials.com', '34,000', 'Gary E. Dickerson'),
('Southwest Airlines', 'LUV', 'Airlines', 'Dallas, Texas', 'https://southwest.com', '74,806', 'Robert E. Jordan'),
('Charles Schwab', 'SCHW', 'Securities', 'Westlake, Texas', 'https://aboutschwab.com', '33,000', 'Walter W. Bettinger'),
('Baker Hughes', 'BKR', 'Oil and Gas Equipment, Services', 'Houston, Texas', 'https://bakerhughes.com', '58,000', 'Lorenzo Simonelli'),
('McDonald''s', 'MCD', 'Food Services', 'Chicago, Illinois', 'https://investor.mcdonalds.com', '150,000', 'Christopher J. Kempczinski'),
('Southern', 'SO', 'Utilities: Gas and Electric', 'Atlanta, Georgia', 'https://southerncompany.com', '27,960', 'Christopher C. Womack'),
('Mastercard', 'MA', 'Financial Data Services', 'Purchase, New York', 'https://mastercard.com', '33,400', 'Michael Miebach'),
('Constellation Energy', 'CEG', 'Energy', 'Baltimore, Maryland', 'https://constellationenergy.com', '13,842', 'Joseph Dominguez'),
('Hartford Financial Services Group', 'HIG', 'Insurance: Property and Casualty (Stock)', 'Hartford, Connecticut', 'https://thehartford.com', '18,700', 'Christopher J. Swift'),
('PG&E', 'PCG', 'Utilities: Gas and Electric', 'Oakland, California', 'https://pgecorp.com', '28,010', 'Patricia K. Poppe'),
('Coupang', 'CPNG', 'Internet Services and Retailing', 'Seattle, Washington', 'https://aboutcoupang.com', '78,000', 'Bom Kim'),
('EOG Resources', 'EOG', 'Mining, Crude-Oil Production', 'Houston, Texas', 'https://eogresources.com', '3,050', 'Ezra Yacob'),
('Union Pacific', 'UNP', 'Railroads', 'Omaha, Nebraska', 'https://up.com', '32,973', 'Jim Vena'),
('Rite Aid', 'RADCQ', 'Food & Drug Stores', 'Philadelphia, Pennsylvania', 'https://riteaid.com', '47,000', 'Jeffrey S. Stein'),
('Macy''s', 'M', 'General Merchandisers', 'New York, New York', 'https://macysinc.com', '85,581', 'Tony Spring'),
('Marriott International', 'MAR', 'Hotels, Casinos, Resorts', 'Bethesda, Maryland', 'https://marriott.com', '148,000', 'Anthony G. Capuano'),
('Lear', 'LEA', 'Motor Vehicles & Parts', 'Southfield, Michigan', 'https://lear.com', '186,600', 'Raymond E. Scott'),
('Genuine Parts', 'GPC', 'Wholesalers: Diversified', 'Atlanta, Georgia', 'https://genpt.com', '60,000', 'Paul Donahue'),
('Sherwin-Williams', 'SHW', 'Chemicals', 'Cleveland, Ohio', 'https://sherwin.com', '64,088', 'Heidi G. Petz'),
('Halliburton', 'HAL', 'Oil and Gas Equipment, Services', 'Houston, Texas', 'https://halliburton.com', '48,000', 'Jeffrey A. Miller'),
('Freeport-McMoRan', 'FCX', 'Mining, Crude-Oil Production', 'Phoenix, Arizona', 'https://fcx.com', '27,200', 'Richard C. Adkerson'),
('Live Nation Entertainment', 'LYV', 'Entertainment', 'Beverly Hills, California', 'https://livenationentertainment.com', '23,200', 'Michael Rapino'),
('Marsh & McLennan', 'MMC', 'Diversified Financials', 'New York, New York', 'https://marshmclennan.com', '85,000', 'John Q. Doyle'),
('Advanced Micro Devices', 'AMD', 'Semiconductors and Other Electronic Components', 'Santa Clara, California', 'https://amd.com', '26,000', 'Lisa T. Su'),
('First Citizens BancShares', 'FCNCA', 'Commercial Banks', 'Raleigh, North Carolina', 'https://firstcitizens.com', '15,868', 'Frank B. Holding'),
('WESCO International', 'WCC', 'Wholesalers: Diversified', 'Pittsburgh, Pennsylvania', 'https://wesco.com', '20,000', 'John J. Engel'),
('Carrier Global', 'CARR', 'Industrial Machinery', 'Palm Beach Gardens, Florida', 'https://corporate.carrier.com', '53,000', 'David L. Gitlin'),
('Cleveland-Cliffs', 'CLF', 'Metals', 'Cleveland, Ohio', 'https://clevelandcliffs.com', '28,000', 'Lourenco Goncalves'),
('Block', 'SQ', 'Financial Data Services', 'Oakland, California', 'https://block.xyz', '12,985', 'Jack Dorsey'),
('Exelon', 'EXC', 'Utilities: Gas and Electric', 'Chicago, Illinois', 'https://exeloncorp.com', '19,962', 'Calvin G. Butler'),
('KKR', 'KKR', 'Securities', 'New York, New York', 'https://kkr.com', '4,490', 'Joseph Y. Bae'),
('CDW', 'CDW', 'Information Technology Services', 'Vernon Hills, Illinois', 'https://cdw.com', '15,100', 'Christine A. Leahy'),
('Booking Holdings', 'BKNG', 'Internet Services and Retailing', 'Norwalk, Connecticut', 'https://bookingholdings.com', '23,482', 'Glenn D. Fogel'),
('Synchrony Financial', 'SYF', 'Diversified Financials', 'Stamford, Connecticut', 'https://synchrony.com', '20,000', 'Brian D. Doubles'),
('Quanta Services', 'PWR', 'Engineering & Construction', 'Houston, Texas', 'https://quantaservices.com', '52,500', 'Earl C. "Duke" Austin'),
('Jones Lang LaSalle', 'JLL', 'Real Estate', 'Chicago, Illinois', 'https://jll.com', '106,100', 'Christian Ulbrich'),
('Discover Financial Services', 'DFS', 'Commercial Banks', 'Riverwoods, Illinois', 'https://discover.com', '21,100', 'J. Michael Shepherd'),
('Tenet Healthcare', 'THC', 'Health Care: Medical Facilities', 'Dallas, Texas', 'https://tenethealth.com', '95,905', 'Saum Sutaria'),
('Altria Group', 'MO', 'Tobacco', 'Richmond, Virginia', 'https://altria.com', '6,400', 'William F. Gifford Jr.'),
('Stryker', 'SYK', 'Medical Products and Equipment', 'Portage, Michigan', 'https://stryker.com', '52,000', 'Kevin A. Lobo'),
('Kimberly-Clark', 'KMB', 'Household and Personal Products', 'Irving, Texas', 'https://kimberly-clark.com', '41,000', 'Mike Hsu'),
('Waste Management', 'WM', 'Waste Management', 'Houston, Texas', 'https://wm.com', '48,000', 'James C. Fish Jr.'),
('Cheniere Energy', 'LNG', 'Pipelines', 'Houston, Texas', 'https://cheniere.com', '1,605', 'Jack A. Fusco'),
('Ross Stores', 'ROST', 'Specialty Retailers: Apparel', 'Dublin, California', 'https://rossstores.com', '108,000', 'Barbara Rentler'),
('WestRock', 'WRK', 'Packaging, Containers', 'Atlanta, Georgia', 'https://westrock.com', '56,100', 'David Sewell'),
('General Mills', 'GIS', 'Food Consumer Products', 'Minneapolis, Minnesota', 'https://generalmills.com', '34,000', 'Jeffrey L. Harmening'),
('Goodyear Tire & Rubber', 'GT', 'Motor Vehicles & Parts', 'Akron, Ohio', 'https://goodyear.com', '71,000', 'Mark W. Stewart'),
('BJ''s Wholesale Club', 'BJ', 'General Merchandisers', 'Marlborough, Massachusetts', 'https://bjs.com', '34,000', 'Robert W. Eddy'),
('GE HealthCare Technologies', 'GEHC', 'Medical Products and Equipment', 'Chicago, Illinois', 'https://gehealthcare.com', '51,000', 'Peter J. Arduini'),
('Colgate-Palmolive', 'CL', 'Household and Personal Products', 'New York, New York', 'https://colgatepalmolive.com', '34,000', 'Noel R. Wallace'),
('Whirlpool', 'WHR', 'Electronics, Electrical Equip.', 'Benton Harbor, Michigan', 'https://whirlpoolcorp.com', '59,000', 'Marc R. Bitzer'),
('L3Harris Technologies', 'LHX', 'Aerospace & Defense', 'Melbourne, Florida', 'https://l3harris.com', '50,000', 'Christopher E. Kubasik'),
('Adobe', 'ADBE', 'Computer Software', 'San Jose, California', 'https://adobe.com', '29,945', 'Shantanu Narayen'),
('Becton Dickinson', 'BDX', 'Medical Products and Equipment', 'Franklin Lakes, New Jersey', 'https://bd.com', '73,000', 'Thomas E. Polen'),
('Cognizant Technology Solutions', 'CTSH', 'Information Technology Services', 'Teaneck, New Jersey', 'https://cognizant.com', '347,700', 'Ravi Kumar Singisetti'),
('Murphy USA', 'MUSA', 'Specialty Retailers: Other', 'El Dorado, Arkansas', 'https://murphyusa.com', '10,750', 'Andrew Clyde'),
('Fiserv', 'FI', 'Financial Data Services', 'Milwaukee, Wisconsin', 'https://fiserv.com', '42,000', 'Frank J. Bisignano'),
('Parker-Hannifin', 'PH', 'Industrial Machinery', 'Cleveland, Ohio', 'https://phstock.com', '62,730', 'Jennifer A. Parmentier'),
('American Electric Power', 'AEP', 'Utilities: Gas and Electric', 'Columbus, Ohio', 'https://aep.com', '17,250', 'Benjamin G.S. Fowke'),
('International Paper', 'IP', 'Packaging, Containers', 'Memphis, Tennessee', 'https://internationalpaper.com', '39,000', 'Andrew K. Silvernail'),
('ManpowerGroup', 'MAN', 'Temporary Help', 'Milwaukee, Wisconsin', 'https://manpowergroup.com', '27,900', 'Jonas Prising'),
('Aramark', 'ARMK', 'Diversified Outsourcing Services', 'Philadelphia, Pennsylvania', 'https://aramark.com', '262,550', 'John J. Zillmer'),
('Steel Dynamics', 'STLD', 'Metals', 'Fort Wayne, Indiana', 'https://steeldynamics.com', '12,600', 'Mark D. Millett'),
('Aflac', 'AFL', 'Insurance: Life, Health (Stock)', 'Columbus, Georgia', 'https://aflac.com', '12,785', 'Daniel P. Amos'),
('Reinsurance Group of America', 'RGA', 'Insurance: Life, Health (Stock)', 'Chesterfield, Missouri', 'https://rgare.com', '3,900', 'Tony Cheng'),
('Emerson Electric', 'EMR', 'Industrial Machinery', 'St. Louis, Missouri', 'https://emerson.com', '67,000', 'Lal L. Karsanbhai'),
('State Street', 'STT', 'Commercial Banks', 'Boston, Massachusetts', 'https://statestreet.com', '46,451', 'Ronald P. O''Hanley'),
('PPG Industries', 'PPG', 'Chemicals', 'Pittsburgh, Pennsylvania', 'https://ppg.com', '53,000', 'Timothy M. Knavish'),
('United States Steel', 'X', 'Metals', 'Pittsburgh, Pennsylvania', 'https://ussteel.com', '21,803', 'David B. Burritt'),
('Automatic Data Processing', 'ADP', 'Diversified Outsourcing Services', 'Roseland, New Jersey', 'https://adp.com', '63,000', 'Maria Black'),
('Group 1 Automotive', 'GPI', 'Automotive Retailing, Services', 'Houston, Texas', 'https://group1auto.com', '16,011', 'Daryl Kenningham'),
('Dominion Energy', 'D', 'Utilities: Gas and Electric', 'Richmond, Virginia', 'https://dominionenergy.com', '17,700', 'Robert M. Blue'),
('BlackRock', 'BLK', 'Securities', 'New York, New York', 'https://blackrock.com', '19,800', 'Laurence D. Fink'),
('Oneok', 'OKE', 'Pipelines', 'Tulsa, Oklahoma', 'https://oneok.com', '4,775', 'Pierce Norton'),
('C.H. Robinson Worldwide', 'CHRW', 'Transportation and Logistics', 'Eden Prairie, Minnesota', 'https://chrobinson.com', '15,246', 'David P. Bozeman'),
('Texas Instruments', 'TXN', 'Semiconductors and Other Electronic Components', 'Dallas, Texas', 'https://ti.com', '34,000', 'Haviv Ilan'),
('Kohl''s', 'KSS', 'General Merchandisers', 'Menomonee Falls, Wisconsin', 'https://kohls.com', '66,000', 'Tom Kingsbury'),
('AutoZone', 'AZO', 'Specialty Retailers: Other', 'Memphis, Tennessee', 'https://autozone.com', '95,200', 'Philip B. Daniele Iii'),
('Lam Research', 'LRCX', 'Semiconductors and Other Electronic Components', 'Fremont, California', 'https://lamresearch.com', '17,200', 'Timothy M. Archer'),
('Corteva', 'CTVA', 'Food Production', 'Indianapolis, Indiana', 'https://corteva.com', '22,500', 'Charles V. Magro'),
('Builders FirstSource', 'BLDR', 'Building Materials, Glass', 'Irving, Texas', 'https://bldr.com', '29,000', 'Dave Rush'),
('Kyndryl Holdings', 'KD', 'Information Technology Services', 'New York, New York', 'https://kyndryl.com', '90,000', 'Martin J. Schroeter'),
('EchoStar', 'SATS', 'Telecommunications', 'Englewood, Colorado', 'https://echostar.com', '15,300', 'Hamid Akhavan'),
('Delek US Holdings', 'DK', 'Petroleum Refining', 'Brentwood, Tennessee', 'https://delekus.com', '3,591', 'Avigal Soreq'),
('Sempra', 'SRE', 'Utilities: Gas and Electric', 'San Diego, California', 'https://sempra.com', '16,835', 'Jeffrey W. Martin'),
('Global Partners', 'GLP', 'Wholesalers: Diversified', 'Waltham, Massachusetts', 'https://globalp.com', '4,273', 'Eric Slifka'),
('W.W. Grainger', 'GWW', 'Wholesalers: Diversified', 'Lake Forest, Illinois', 'https://grainger.com', '24,650', 'Donald G. Macpherson'),
('Jacobs Solutions', 'J', 'Diversified Outsourcing Services', 'Dallas, Texas', 'https://jacobs.com', '58,550', 'Bob Pragada'),
('Edison International', 'EIX', 'Utilities: Gas and Electric', 'Rosemead, California', 'https://edisoninvestor.com', '14,346', 'Pedro J. Pizarro'),
('MGM Resorts International', 'MGM', 'Hotels, Casinos, Resorts', 'Las Vegas, Nevada', 'https://mgmresorts.com', '67,000', 'William J. Hornbuckle'),
('Illinois Tool Works', 'ITW', 'Industrial Machinery', 'Glenview, Illinois', 'https://itw.com', '45,000', 'Christopher A. O''Herlihy'),
('Ameriprise Financial', 'AMP', 'Diversified Financials', 'Minneapolis, Minnesota', 'https://ameriprise.com', '13,800', 'James M. Cracchiolo'),
('PulteGroup', 'PHM', 'Homebuilders', 'Atlanta, Georgia', 'https://pultegroupinc.com', '6,382', 'Ryan R. Marshall'),
('Targa Resources', 'TRGP', 'Pipelines', 'Houston, Texas', 'https://targaresources.com', '3,182', 'Matthew J. Meloy'),
('Ally Financial', 'ALLY', 'Diversified Financials', 'Detroit, Michigan', 'https://ally.com', '11,100', 'Michael G. Rhodes'),
('BorgWarner', 'BWA', 'Motor Vehicles & Parts', 'Auburn Hills, Michigan', 'https://borgwarner.com', '39,900', 'Frederic B. Lissalde'),
('Estée Lauder', 'EL', 'Household and Personal Products', 'New York, New York', 'https://elcompanies.com', '53,010', 'Fabrizio Freda'),
('Loews', 'L', 'Insurance: Property and Casualty (Stock)', 'New York, New York', 'https://loews.com', '12,280', 'James S. Tisch'),
('O''Reilly Automotive', 'ORLY', 'Specialty Retailers: Other', 'Springfield, Missouri', 'https://oreillyauto.com', '82,958', 'Brad Beckham'),
('Markel Group', 'MKL', 'Insurance: Property and Casualty (Stock)', 'Glen Allen, Virginia', 'https://mklgroup.com', '21,600', 'Thomas S. Gayner'),
('Stanley Black & Decker', 'SWK', 'Home Equipment, Furnishings', 'New Britain, Connecticut', 'https://stanleyblackanddecker.com', '50,500', 'Donald Allan'),
('Micron Technology', 'MU', 'Semiconductors and Other Electronic Components', 'Boise, Idaho', 'https://micron.com', '43,000', 'Sanjay Mehrotra'),
('Fluor', 'FLR', 'Engineering & Construction', 'Irving, Texas', 'https://fluor.com', '30,187', 'David E. Constable'),
('Leidos Holdings', 'LDOS', 'Information Technology Services', 'Reston, Virginia', 'https://leidos.com', '47,000', 'Thomas A. Bell'),
('Viatris', 'VTRS', 'Pharmaceuticals', 'Canonsburg, Pennsylvania', 'https://viatris.com', '38,000', 'Scott A. Smith'),
('Kinder Morgan', 'KMI', 'Pipelines', 'Houston, Texas', 'https://kindermorgan.com', '10,891', 'Kimberly A. Dang'),
('Ecolab', 'ECL', 'Chemicals', 'St. Paul, Minnesota', 'https://ecolab.com', '48,000', 'Christophe Beck'),
('Baxter International', 'BAX', 'Medical Products and Equipment', 'Deerfield, Illinois', 'https://baxter.com', '60,000', 'Jose E. Almeida'),
('Devon Energy', 'DVN', 'Mining, Crude-Oil Production', 'Oklahoma City, Oklahoma', 'https://devonenergy.com', '1,900', 'Richard E. Muncrief'),
('Kellanova', 'K', 'Food Consumer Products', 'Chicago, Illinois', 'http://kellanova.com', '23,000', 'Steven A. Cahillane'),
('Casey''s General Stores', 'CASY', 'Specialty Retailers: Other', 'Ankeny, Iowa', 'https://caseys.com', '31,637', 'Darren M. Rebelez'),
('IQVIA Holdings', 'IQV', 'Health Care: Pharmacy and Other Services', 'Durham, North Carolina', 'https://iqvia.com', '87,000', 'Ari Bousbib'),
('Republic Services', 'RSG', 'Waste Management', 'Phoenix, Arizona', 'https://republicservices.com', '41,000', 'Jon Vander Ark'),
('Fox', 'FOXA', 'Entertainment', 'New York, New York', 'https://foxcorporation.com', '10,400', 'Lachlan K. Murdoch'),
('Gap', 'GPS', 'Specialty Retailers: Apparel', 'San Francisco, California', 'https://gapinc.com', '85,000', 'Richard Dickson'),
('Keurig Dr Pepper', 'KDP', 'Beverages', 'Burlington, Massachusetts', 'https://keurig.com', '28,100', 'Robert J. Gamgort'),
('Reliance', 'RS', 'Metals', 'Scottsdale, Arizona', 'https://reliance.com', '15,250', 'Karla R. Lewis'),
('Asbury Automotive Group', 'ABG', 'Automotive Retailing, Services', 'Duluth, Georgia', 'https://asburyauto.com', '15,000', 'David W. Hult'),
('Vistra', 'VST', 'Energy', 'Irving, Texas', 'https://vistracorp.com', '4,870', 'James A. Burke'),
('Andersons', 'ANDE', 'Food Production', 'Maumee, Ohio', 'https://andersonsinc.com', '2,297', 'Patrick E. Bowe'),
('Nordstrom', 'JWN', 'General Merchandisers', 'Seattle, Washington', 'https://nordstrom.com', '54,000', 'Erik B. Nordstrom'),
('Omnicom Group', 'OMC', 'Advertising, Marketing', 'New York, New York', 'https://omnicomgroup.com', '75,900', 'John D. Wren'),
('Fidelity National Information Services', 'FIS', 'Financial Data Services', 'Jacksonville, Florida', 'https://fisglobal.com', '60,000', 'Stephanie Ferris'),
('Consolidated Edison', 'ED', 'Utilities: Gas and Electric', 'New York, New York', 'https://conedison.com', '14,592', 'Timothy P. Cawley'),
('CSX', 'CSX', 'Railroads', 'Jacksonville, Florida', 'https://csx.com', '23,232', 'Joseph R. Hinrichs'),
('AECOM', 'ACM', 'Engineering & Construction', 'Dallas, Texas', 'https://aecom.com', '52,000', 'Troy Rudd'),
('Lumen Technologies', 'LUMN', 'Telecommunications', 'Monroe, Louisiana', 'https://lumen.com', '28,000', 'Kathleen E. Johnson'),
('Tractor Supply', 'TSCO', 'Specialty Retailers: Other', 'Brentwood, Tennessee', 'https://tractorsupply.com', '37,500', 'Harry A. Lawton Iii'),
('DXC Technology', 'DXC', 'Information Technology Services', 'Ashburn, Virginia', 'https://dxc.technology', '130,000', 'Raul J. Fernandez'),
('AGCO', 'AGCO', 'Construction and Farm Machinery', 'Duluth, Georgia', 'https://agcocorp.com', '27,900', 'Eric P. Hansotia'),
('Sonic Automotive', 'SAH', 'Automotive Retailing, Services', 'Charlotte, North Carolina', 'https://sonicautomotive.com', '10,500', 'David Bruton Smith'),
('Intuit', 'INTU', 'Computer Software', 'Mountain View, California', 'https://intuit.com', '22,900', 'Sasan K. Goodarzi'),
('United Rentals', 'URI', 'Equipment Leasing', 'Stamford, Connecticut', 'https://unitedrentals.com', '26,300', 'Matthew J. Flannery'),
('Universal Health Services', 'UHS', 'Health Care: Medical Facilities', 'King of Prussia, Pennsylvania', 'https://uhs.com', '85,025', 'Marc D. Miller'),
('Boston Scientific', 'BSX', 'Medical Products and Equipment', 'Marlborough, Massachusetts', 'https://bostonscientific.com', '48,000', 'Michael F. Mahoney'),
('Otis Worldwide', 'OTIS', 'Industrial Machinery', 'Farmington, Connecticut', 'https://otis.com', '71,000', 'Judith F. Marks'),
('Xcel Energy', 'XEL', 'Utilities: Gas and Electric', 'Minneapolis, Minnesota', 'https://xcelenergy.com', '11,311', 'Bob Frenzel'),
('Ball', 'BALL', 'Packaging, Containers', 'Westminster, Colorado', 'https://ball.com', '21,000', 'Daniel W. Fisher'),
('LKQ', 'LKQ', 'Wholesalers: Diversified', 'Chicago, Illinois', 'https://lkqcorp.com', '49,000', 'Dominick P. Zarcone'),
('Mosaic', 'MOS', 'Chemicals', 'Tampa, Florida', 'https://mosaicco.com', '14,049', 'Bruce M. Bodine'),
('Textron', 'TXT', 'Aerospace & Defense', 'Providence, Rhode Island', 'https://textron.com', '35,000', 'Scott C. Donnelly'),
('Laboratory Corp. of America', 'LH', 'Health Care: Pharmacy and Other Services', 'Burlington, North Carolina', 'https://labcorp.com', '61,975', 'Adam H. Schechter'),
('Principal Financial', 'PFG', 'Insurance: Life, Health (Stock)', 'Des Moines, Iowa', 'https://principal.com', '19,800', 'Daniel J. Houston'),
('Regeneron Pharmaceuticals', 'REGN', 'Pharmaceuticals', 'Tarrytown, New York', 'https://regeneron.com', '13,450', 'Leonard S. Schleifer'),
('Raymond James Financial', 'RJF', 'Securities', 'St. Petersburg, Florida', 'https://raymondjames.com', '18,000', 'Paul C. Reilly'),
('Dick''s Sporting Goods', 'DKS', 'Specialty Retailers: Other', 'Coraopolis, Pennsylvania', 'https://dickssportinggoods.com', '37,200', 'Lauren R. Hobart'),
('Expedia Group', 'EXPE', 'Internet Services and Retailing', 'Seattle, Washington', 'https://expediagroup.com', '17,100', 'Ariane Gorin'),
('J.B. Hunt Transport Services', 'JBHT', 'Trucking, Truck Leasing', 'Lowell, Arkansas', 'https://jbhunt.com', '34,718', 'John N. Roberts Iii'),
('M&T Bank', 'MTB', 'Commercial Banks', 'Buffalo, New York', 'https://mtb.com', '21,980', 'Rene F. Jones'),
('DTE Energy', 'DTE', 'Utilities: Gas and Electric', 'Detroit, Michigan', 'https://dteenergy.com', '9,950', 'Gerardo Norcia'),
('AES', 'AES', 'Utilities: Gas and Electric', 'Arlington, Virginia', 'https://aes.com', '9,600', 'Andres R. Gluski'),
('Berry Global Group', 'BERY', 'Packaging, Containers', 'Evansville, Indiana', 'https://berryglobal.com', '44,000', 'Kevin Kwilinski'),
('Fifth Third Bancorp', 'FITB', 'Commercial Banks', 'Cincinnati, Ohio', 'https://53.com', '18,724', 'Timothy N. Spence'),
('Air Products & Chemicals', 'APD', 'Chemicals', 'Allentown, Pennsylvania', 'https://airproducts.com', '21,850', 'Seifi Ghasemi'),
('Corning', 'GLW', 'Electronics, Electrical Equip.', 'Corning, New York', 'https://corning.com', '49,800', 'Wendell P. Weeks'),
('EMCOR Group', 'EME', 'Engineering & Construction', 'Norwalk, Connecticut', 'https://emcorgroup.com', '38,300', 'Anthony J. Guzzi'),
('Amphenol', 'APH', 'Network and Other Communications Equipment', 'Wallingford, Connecticut', 'https://amphenol.com', '95,000', 'Adam Norwitt'),
('Westlake', 'WLK', 'Chemicals', 'Houston, Texas', 'https://westlake.com', '15,520', 'Albert Yuan Chao'),
('DuPont', 'DD', 'Chemicals', 'Wilmington, Delaware', 'https://dupont.com', '24,000', 'Edward D. Breen'),
('Liberty Media', 'LSXMA', 'Entertainment', 'Englewood, Colorado', 'https://libertymedia.com', '6,486', 'Gregory B. Maffei'),
('S&P Global', 'SPGI', 'Financial Data Services', 'New York, New York', 'https://spglobal.com', '40,450', 'Douglas L. Peterson'),
('Community Health Systems', 'CYH', 'Health Care: Medical Facilities', 'Franklin, Tennessee', 'https://chs.net', '54,500', 'Tim L. Hingtgen'),
('FirstEnergy', 'FE', 'Utilities: Gas and Electric', 'Akron, Ohio', 'https://firstenergycorp.com', '12,042', 'Brian X. Tierney'),
('Unum Group', 'UNM', 'Insurance: Life, Health (Stock)', 'Chattanooga, Tennessee', 'https://unum.com', '10,683', 'Richard P. Mckenney'),
('Henry Schein', 'HSIC', 'Wholesalers: Health Care', 'Melville, New York', 'https://henryschein.com', '25,000', 'Stanley M. Bergman'),
('Western Digital', 'WDC', 'Computers, Office Equipment', 'San Jose, California', 'https://westerndigital.com', '53,000', 'David V. Goeckeler'),
('Analog Devices', 'ADI', 'Semiconductors and Other Electronic Components', 'Wilmington, Massachusetts', 'https://analog.com', '26,000', 'Vincent T. Roche'),
('Conagra Brands', 'CAG', 'Food Consumer Products', 'Chicago, Illinois', 'https://conagrabrands.com', '18,600', 'Sean M. Connolly'),
('Citizens Financial Group', 'CFG', 'Commercial Banks', 'Providence, Rhode Island', 'https://citizensbank.com', '17,570', 'Bruce W. Van Saun'),
('Norfolk Southern', 'NSC', 'Railroads', 'Atlanta, Georgia', 'https://norfolksouthern.com', '20,700', 'Alan H. Shaw'),
('Entergy', 'ETR', 'Utilities: Gas and Electric', 'New Orleans, Louisiana', 'https://entergy.com', '12,177', 'Andrew S. Marsh'),
('W.R. Berkley', 'WRB', 'Insurance: Property and Casualty (Stock)', 'Greenwich, Connecticut', 'https://berkley.com', '8,329', 'Robert Berkley'),
('DaVita', 'DVA', 'Health Care: Medical Facilities', 'Denver, Colorado', 'https://davita.com', '70,000', 'Javier J. Rodriguez'),
('Northern Trust', 'NTRS', 'Commercial Banks', 'Chicago, Illinois', 'https://northerntrust.com', '23,100', 'Michael G. O''Grady'),
('Hormel Foods', 'HRL', 'Food Consumer Products', 'Austin, Minnesota', 'https://hormelfoods.com', '20,000', 'Jim(James) Snee'),
('Crown Holdings', 'CCK', 'Packaging, Containers', 'Tampa, Florida', 'https://crowncork.com', '25,000', 'Timothy J. Donahue'),
('Avis Budget Group', 'CAR', 'Automotive Retailing, Services', 'Parsippany, New Jersey', 'https://avisbudgetgroup.com', '21,250', 'NULL'),
('Wayfair', 'W', 'Internet Services and Retailing', 'Boston, Massachusetts', 'https://wayfair.com', '12,800', 'Niraj S. Shah'),
('MasTec', 'MTZ', 'Engineering & Construction', 'Coral Gables, Florida', 'https://mastec.com', '34,000', 'Jose R. Mas'),
('Eversource Energy', 'ES', 'Utilities: Gas and Electric', 'Springfield, Massachusetts', 'https://eversource.com', '10,171', 'Joseph R. Nolan'),
('Newmont', 'NEM', 'Mining, Crude-Oil Production', 'Denver, Colorado', 'https://newmont.com', '21,700', 'Thomas R. Palmer'),
('Ryder System', 'R', 'Transportation and Logistics', 'Coral Gables, Florida', 'https://ryder.com', '47,500', 'Robert E. Sanchez'),
('Fidelity National Financial', 'FNF', 'Insurance: Property and Casualty (Stock)', 'Jacksonville, Florida', 'https://fnf.com', '22,293', 'Michael J. Nolan'),
('Molson Coors Beverage', 'TAP', 'Beverages', 'Chicago, Illinois', 'https://molsoncoors.com', '16,500', 'Gavin D.K. Hattersley'),
('Caesars Entertainment', 'CZR', 'Hotels, Casinos, Resorts', 'Reno, Nevada', 'https://caesars.com', '51,000', 'Thomas R. Reeg'),
('Lincoln National', 'LNC', 'Insurance: Life, Health (Stock)', 'Radnor, Pennsylvania', 'https://lincolnfinancial.com', '11,024', 'Ellen G. Cooper'),
('VF', 'VFC', 'Apparel', 'Denver, Colorado', 'https://vfc.com', '26,400', 'Bracken P. Darrell'),
('International Flavors & Fragrances', 'IFF', 'Chemicals', 'New York, New York', 'https://iff.com', '21,500', 'J. Erik Fyrwald'),
('Huntington Ingalls Industries', 'HII', 'Aerospace & Defense', 'Newport News, Virginia', 'https://hii.com', '44,000', 'Christopher D. Kastner'),
('Advance Auto Parts', 'AAP', 'Specialty Retailers: Other', 'Raleigh, North Carolina', 'https://advanceautoparts.com', '54,500', 'Shane M. O''Kelly'),
('Public Service Enterprise Group', 'PEG', 'Utilities: Gas and Electric', 'Newark, New Jersey', 'https://pseg.com', '12,543', 'Ralph A. Larossa'),
('Ulta Beauty', 'ULTA', 'Specialty Retailers: Other', 'Bolingbrook, Illinois', 'https://ulta.com', '38,000', 'David C. Kimbell'),
('Hershey', 'HSY', 'Food Consumer Products', 'Hershey, Pennsylvania', 'https://thehersheycompany.com', '19,578', 'Michele G. Buck'),
('Chewy', 'CHWY', 'Internet Services and Retailing', 'Plantation, Florida', 'https://chewy.com', '18,100', 'Sumit Singh'),
('American Tower', 'AMT', 'Real Estate', 'Boston, Massachusetts', 'https://americantower.com', '5,643', 'Steven O. Vondran'),
('Mohawk Industries', 'MHK', 'Home Equipment, Furnishings', 'Calhoun, Georgia', 'https://mohawkind.com', '43,300', 'Jeffrey S. Lorberbaum'),
('Assurant', 'AIZ', 'Insurance: Property and Casualty (Stock)', 'Atlanta, Georgia', 'https://assurant.com', '13,600', 'Keith W. Demmings'),
('THOR Industries', 'THO', 'Motor Vehicles & Parts', 'Elkhart, Indiana', 'https://thorindustries.com', '24,900', 'Robert W. Martin'),
('Yum China Holdings', 'YUMC', 'Food Services', 'Plano, Texas', 'https://ir.yumchina.com', '293,500', 'Joey Wat'),
('Celanese', 'CE', 'Chemicals', 'Irving, Texas', 'https://celanese.com', '12,410', 'Lori J. Ryerkerk'),
('Qurate Retail', 'QRTEA', 'Internet Services and Retailing', 'Englewood, Colorado', 'https://qurateretail.com', '20,386', 'David Rawlinson Ii'),
('Williams', 'WMB', 'Pipelines', 'Tulsa, Oklahoma', 'https://williams.com', '5,601', 'Alan S. Armstrong'),
('Interpublic Group', 'IPG', 'Advertising, Marketing', 'New York, New York', 'https://interpublic.com', '57,400', 'Phillippe Krakowsky'),
('Ovintiv', 'OVV', 'Mining, Crude-Oil Production', 'Denver, Colorado', 'https://ovintiv.com', '1,743', 'Brendan M. Mccracken'),
('Icahn Enterprises', 'IEP', 'Diversified Financials', 'Sunny Isles Beach, Florida', 'https://ielp.com', '15,038', 'Andrew Teno'),
('Huntington Bancshares', 'HBAN', 'Commercial Banks', 'Columbus, Ohio', 'https://huntington.com', '19,955', 'Stephen D. Steinour'),
('Carvana', 'CVNA', 'Automotive Retailing, Services', 'Tempe, Arizona', 'https://carvana.com', '13,700', 'Ernest C. Garcia Iii'),
('Hess', 'HES', 'Mining, Crude-Oil Production', 'New York, New York', 'https://hess.com', '1,756', 'John B. Hess'),
('Dana', 'DAN', 'Motor Vehicles & Parts', 'Maumee, Ohio', 'https://dana.com', '41,800', 'James K. Kamsickas'),
('Alcoa', 'AA', 'Metals', 'Pittsburgh, Pennsylvania', 'https://alcoa.com', '13,600', 'William F. Oplinger'),
('Equitable Holdings', 'EQH', 'Insurance: Life, Health (Stock)', 'New York, New York', 'https://equitableholdings.com', '10,700', 'Mark Pearson'),
('KLA', 'KLAC', 'Semiconductors and Other Electronic Components', 'Milpitas, California', 'https://kla.com', '15,105', 'Rick Wallace'),
('Darden Restaurants', 'DRI', 'Food Services', 'Orlando, Florida', 'https://darden.com', '187,384', 'Ricardo Cardenas'),
('Autoliv', 'ALV', 'Motor Vehicles & Parts', 'Auburn Hills, Michigan', 'https://autoliv.com', '66,434', 'Mikael Bratt'),
('Alaska Air Group', 'ALK', 'Airlines', 'Seattle, Washington', 'https://alaskaair.com', '24,610', 'Benito Minicucci'),
('KeyCorp', 'KEY', 'Commercial Banks', 'Cleveland, Ohio', 'https://key.com', '17,692', 'Christopher M. Gorman'),
('Las Vegas Sands', 'LVS', 'Hotels, Casinos, Resorts', 'Las Vegas, Nevada', 'https://sands.com', '38,550', 'Robert G. Goldstein'),
('Owens & Minor', 'OMI', 'Wholesalers: Health Care', 'Mechanicsville, Virginia', 'https://owens-minor.com', '22,200', 'Edward A. Pesicka'),
('Hilton Worldwide Holdings', 'HLT', 'Hotels, Casinos, Resorts', 'McLean, Virginia', 'https://hilton.com', '178,000', 'Christopher J. Nassetta'),
('Ebay', 'EBAY', 'Internet Services and Retailing', 'San Jose, California', 'https://ebay.com', '12,300', 'Jamie Iannone'),
('Arthur J. Gallagher', 'AJG', 'Diversified Financials', 'Rolling Meadows, Illinois', 'https://ajg.com', '52,118', 'Patrick Gallagher'),
('LPL Financial Holdings', 'LPLA', 'Securities', 'San Diego, California', 'https://lpl.com', '7,372', 'Dan H. Arnold'),
('Cincinnati Financial', 'CINF', 'Insurance: Property and Casualty (Stock)', 'Fairfield, Ohio', 'https://cinfin.com', '5,426', 'Stephen M. Spray'),
('Toll Brothers', 'TOL', 'Homebuilders', 'Fort Washington, Pennsylvania', 'https://tollbrothers.com', '4,800', 'Douglas C. Yearley Jr.'),
('Motorola Solutions', 'MSI', 'Network and Other Communications Equipment', 'Chicago, Illinois', 'https://motorolasolutions.com', '21,000', 'Gregory Q. Brown'),
('Airbnb', 'ABNB', 'Internet Services and Retailing', 'San Francisco, California', 'https://airbnb.com', '6,907', 'Brian Chesky'),
('Intercontinental Exchange', 'ICE', 'Securities', 'Atlanta, Georgia', 'https://ice.com', '13,222', 'Jeffrey C. Sprecher'),
('News Corp.', 'NWSA', 'Publishing, Printing', 'New York, New York', 'https://newscorp.com', '25,000', 'Robert J. Thomson'),
('Chipotle Mexican Grill', 'CMG', 'Food Services', 'Newport Beach, California', 'https://chipotle.com', '116,068', 'Brian R. Niccol'),
('Vertex Pharmaceuticals', 'VRTX', 'Pharmaceuticals', 'Boston, Massachusetts', 'https://vrtx.com', '5,400', 'Reshma Kewalramani'),
('Biogen', 'BIIB', 'Pharmaceuticals', 'Cambridge, Massachusetts', 'https://biogen.com', '7,570', 'Christopher A. Viehbacher'),
('GXO Logistics', 'GXO', 'Transportation and Logistics', 'Greenwich, Connecticut', 'https://gxo.com', '109,000', 'Malcolm Wilson'),
('SpartanNash', 'SPTN', 'Wholesalers: Food and Grocery', 'Grand Rapids, Michigan', 'https://spartannash.com', '13,500', 'Tony Sarsam'),
('Burlington Stores', 'BURL', 'Specialty Retailers: Apparel', 'Burlington, New Jersey', 'https://burlingtoninvestors.com', '44,050', 'Michael B. O’Sullivan'),
('NVR', 'NVR', 'Homebuilders', 'Reston, Virginia', 'https://nvrinc.com', '6,300', 'Eugene J. Bredow'),
('Owens Corning', 'OC', 'Building Materials, Glass', 'Toledo, Ohio', 'https://owenscorning.com', '18,000', 'Brian D. Chambers'),
('Westinghouse Air Brake Technologies', 'WAB', 'Industrial Machinery', 'Pittsburgh, Pennsylvania', 'https://wabteccorp.com', '29,000', 'Rafael O. Santana'),
('Oshkosh', 'OSK', 'Construction and Farm Machinery', 'Oshkosh, Wisconsin', 'https://oshkoshcorp.com', '17,300', 'John C. Pfeifer'),
('Global Payments', 'GPN', 'Financial Data Services', 'Atlanta, Georgia', 'https://globalpaymentsinc.com', '27,000', 'Cameron M. Bready'),
('Lululemon athletica', 'LULU', 'Specialty Retailers: Apparel', 'Sumner, Washington', 'https://lululemon.com', '38,000', 'Calvin Mcdonald'),
('Albemarle', 'ALB', 'Chemicals', 'Charlotte, North Carolina', 'https://albemarle.com', '9,000', 'Kent Masters'),
('JetBlue Airways', 'JBLU', 'Airlines', 'Long Island City, New York', 'https://jetblue.com', '21,310', 'Joanna Geraghty'),
('Seaboard', 'SEB', 'Food Production', 'Merriam, Kansas', 'https://seaboardcorp.com', '12,847', 'Robert L. Steer'),
('Constellation Brands', 'STZ', 'Beverages', 'Victor, New York', 'https://cbrands.com', '9,400', 'William A. Newlands'),
('Graphic Packaging Holding', 'GPK', 'Packaging, Containers', 'Atlanta, Georgia', 'https://graphicpkg.com', '23,500', 'Michael Doss'),
('Hertz Global Holdings', 'HTZ', 'Automotive Retailing, Services', 'Estero, Florida', 'https://hertz.com', '27,000', 'Gil West'),
('Campbell Soup', 'CPB', 'Food Consumer Products', 'Camden, New Jersey', 'https://campbellsoupcompany.com', '14,500', 'Mark A. Clouse'),
('Expeditors International of Washington', 'EXPD', 'Transportation and Logistics', 'Seattle, Washington', 'https://expeditors.com', '18,452', 'Jeffrey S. Musser'),
('A-Mark Precious Metals', 'AMRK', 'Wholesalers: Diversified', 'El Segundo, California', 'https://amark.com', '421', 'Gregory N. Roberts'),
('Booz Allen Hamilton Holding', 'BAH', 'Information Technology Services', 'McLean, Virginia', 'https://boozallen.com', '31,900', 'Horacio D. Rozanski'),
('Quest Diagnostics', 'DGX', 'Health Care: Pharmacy and Other Services', 'Secaucus, New Jersey', 'https://questdiagnostics.com', '44,000', 'James E. Davis'),
('Altice USA', 'ATUS', 'Telecommunications', 'Long Island City, New York', 'https://alticeusa.com', '10,600', 'Dennis Mathew'),
('PVH', 'PVH', 'Apparel', 'New York, New York', 'https://pvh.com', '23,000', 'Stefan Larsson'),
('Eastman Chemical', 'EMN', 'Chemicals', 'Kingsport, Tennessee', 'https://eastman.com', '14,000', 'Mark J. Costa'),
('Insight Enterprises', 'NSIT', 'Information Technology Services', 'Chandler, Arizona', 'https://insight.com', '14,437', 'Joyce Mullen'),
('Regions Financial', 'RF', 'Commercial Banks', 'Birmingham, Alabama', 'https://regions.com', '20,101', 'John M. Turner Jr.'),
('Beacon Roofing Supply', 'BECN', 'Wholesalers: Diversified', 'Herndon, Virginia', 'https://becn.com', '8,063', 'Julian G. Francis'),
('Rockwell Automation', 'ROK', 'Electronics, Electrical Equip.', 'Milwaukee, Wisconsin', 'https://rockwellautomation.com', '29,000', 'Blake D. Moret'),
('Polaris', 'PII', 'Transportation Equipment', 'Medina, Minnesota', 'https://polaris.com', '18,500', 'Michael T. Speetzen'),
('ServiceNow', 'NOW', 'Computer Software', 'Santa Clara, California', 'https://servicenow.com', '22,668', 'Bill Mcdermott'),
('Sanmina', 'SANM', 'Semiconductors and Other Electronic Components', 'San Jose, California', 'https://sanmina.com', '36,000', 'Jure Sola'),
('UGI', 'UGI', 'Utilities: Gas and Electric', 'King of Prussia, Pennsylvania', 'https://ugicorp.com', '10,500', 'Mario Longhi'),
('WEC Energy Group', 'WEC', 'Utilities: Gas and Electric', 'Milwaukee, Wisconsin', 'https://wecenergygroup.com', '7,000', 'Scott J. Lauber'),
('BrightSpring Health Services', 'BGST', 'Health Care: Pharmacy and Other Services', 'Louisville, Kentucky', 'https://brightspringhealth.com', '35,000', 'Jon B. Rousseau'),
('Cintas', 'CTAS', 'Diversified Outsourcing Services', 'Cincinnati, Ohio', 'https://cintas.com', '44,500', 'Todd M. Schneider'),
('Commercial Metals', 'CMC', 'Metals', 'Irving, Texas', 'https://cmc.com', '13,022', 'Peter R. Matt'),
('Chesapeake Energy', 'CHK', 'Mining, Crude-Oil Production', 'Oklahoma City, Oklahoma', 'https://chk.com', '1,000', 'Domenic J. Dell''Osso'),
('CenterPoint Energy', 'CNP', 'Utilities: Gas and Electric', 'Houston, Texas', 'https://centerpointenergy.com', '8,827', 'Jason P. Wells'),
('NGL Energy Partners', 'NGL', 'Pipelines', 'Tulsa, Oklahoma', 'https://nglenergypartners.com', '638', 'Michael Krimbill'),
('DoorDash', 'DASH', 'Internet Services and Retailing', 'San Francisco, California', 'https://ir.doordash.com', '19,300', 'Tony Xu'),
('NOV', 'NOV', 'Oil and Gas Equipment, Services', 'Houston, Texas', 'https://nov.com', '33,676', 'Clay C. Williams'),
('Zoetis', 'ZTS', 'Pharmaceuticals', 'Parsippany, New Jersey', 'https://zoetis.com', '14,100', 'Kristin C. Peck'),
('J.M. Smucker', 'SJM', 'Food Consumer Products', 'Orrville, Ohio', 'https://jmsmucker.com', '5,800', 'Mark T. Smucker'),
('Microchip Technology', 'MCHP', 'Semiconductors and Other Electronic Components', 'Chandler, Arizona', 'https://microchip.com', '22,600', 'Ganesh Moorthy'),
('Dover', 'DOV', 'Industrial Machinery', 'Downers Grove, Illinois', 'https://dovercorporation.com', '25,000', 'Richard J. Tobin'),
('Diamondback Energy', 'FANG', 'Mining, Crude-Oil Production', 'Midland, Texas', 'https://diamondbackenergy.com', '1,023', 'Travis D. Stice'),
('Avery Dennison', 'AVY', 'Packaging, Containers', 'Mentor, Ohio', 'https://averydennison.com', '35,000', 'Dean M. Stander'),
('PPL', 'PPL', 'Utilities: Gas and Electric', 'Allentown, Pennsylvania', 'https://pplweb.com', '6,629', 'Vincent Sorgi'),
('ON Semiconductor', 'ON', 'Semiconductors and Other Electronic Components', 'Scottsdale, Arizona', 'https://onsemi.com', '30,050', 'Hassane El-Khoury'),
('ARKO', 'ARKO', 'Specialty Retailers: Other', 'Richmond, Virginia', 'https://arkocorp.com', '13,481', 'Arie Kotler'),
('Par Pacific Holdings', 'PARR', 'Petroleum Refining', 'Houston, Texas', 'https://parpacific.com', '1,814', 'William C. Pate'),
('APA', 'APA', 'Mining, Crude-Oil Production', 'Houston, Texas', 'https://apacorp.com', '2,271', 'John J. Christmann Iv'),
('Equinix', 'EQIX', 'Real Estate', 'Redwood City, California', 'https://equinix.com', '13,151', 'Charles Meyers'),
('New York Community Bancorp', 'NYCB', 'Commercial Banks', 'Hicksville, New York', 'https://mynycb.com', '8,766', 'Joseph M. Otting'),
('Foot Locker', 'FL', 'Specialty Retailers: Apparel', 'New York, New York', 'https://footlocker.com/corp', '30,591', 'Mary N. Dillon'),
('Ingredion', 'INGR', 'Food Production', 'Westchester, Illinois', 'https://ingredion.com', '11,600', 'James (Jim) Zallie'),
('Newell Brands', 'NWL', 'Home Equipment, Furnishings', 'Atlanta, Georgia', 'https://newellbrands.com', '24,600', 'Christopher H. Peterson'),
('ABM Industries', 'ABM', 'Diversified Outsourcing Services', 'New York, New York', 'https://abm.com', '123,000', 'Scott B. Salmirs'),
('Prologis', 'PLD', 'Real Estate', 'San Francisco, California', 'https://prologis.com', '2,574', 'Hamid R. Moghadam'),
('Blackstone', 'BX', 'Diversified Financials', 'New York, New York', 'https://blackstone.com', '4,735', 'Stephen A. Schwarzman'),
('Skechers U.S.A.', 'SKX', 'Apparel', 'Manhattan Beach, California', 'https://skechers.com', '13,550', 'Robert Greenberg'),
('Masco', 'MAS', 'Home Equipment, Furnishings', 'Livonia, Michigan', 'https://masco.com', '18,000', 'Keith J. Allman'),
('Rush Enterprises', 'RUSHB', 'Automotive Retailing, Services', 'New Braunfels, Texas', 'https://rushenterprises.com', '8,449', 'W.M. Rush'),
('Franklin Resources', 'BEN', 'Securities', 'San Mateo, California', 'https://franklinresources.com', '9,200', 'Jenny Johnson'),
('ODP', 'ODP', 'Specialty Retailers: Other', 'Boca Raton, Florida', 'https://theodpcorp.com', '20,000', 'Gerry P. Smith'),
('American Financial Group', 'AFG', 'Insurance: Property and Casualty (Stock)', 'Cincinnati, Ohio', 'https://afginc.com', '8,500', 'Carl H. Lindner Lll'),
('Packaging Corp. of America', 'PKG', 'Packaging, Containers', 'Lake Forest, Illinois', 'https://packagingcorp.com', '14,900', 'Mark W. Kowlzan'),
('Vulcan Materials', 'VMC', 'Building Materials, Glass', 'Birmingham, Alabama', 'https://vulcanmaterials.com', '10,961', 'Thomas Hill'),
('Interactive Brokers Group', 'IBKR', 'Securities', 'Greenwich, Connecticut', 'https://interactivebrokers.com', '2,932', 'Milan Galik'),
('Williams-Sonoma', 'WSM', 'Specialty Retailers: Other', 'San Francisco, California', 'https://williams-sonomainc.com', '15,000', 'Laura J. Alber'),
('XPO', 'XPO', 'Transportation and Logistics', 'Greenwich, Connecticut', 'https://xpo.com', '39,450', 'Mario A. Harik'),
('Weyerhaeuser', 'WY', 'Forest and Paper Products', 'Seattle, Washington', 'https://weyerhaeuser.com', '9,318', 'Devin W. Stockfish'),
('Genworth Financial', 'GNW', 'Insurance: Life, Health (Stock)', 'Richmond, Virginia', 'https://genworth.com', '2,700', 'Thomas J. Mcinerney'),
('CMS Energy', 'CMS', 'Utilities: Gas and Electric', 'Jackson, Michigan', 'https://cmsenergy.com', '8,356', 'Garrick J. Rochow'),
('Science Applications International', 'SAIC', 'Information Technology Services', 'Reston, Virginia', 'https://saic.com', '24,000', 'Toni Townes-Whitley'),
('Jefferies Financial Group', 'JEF', 'Diversified Financials', 'New York, New York', 'https://jefferies.com', '7,564', 'Richard B. Handler'),
('Bath & Body Works', 'BBWI', 'Specialty Retailers: Other', 'Columbus, Ohio', 'https://bbwinc.com', '33,069', 'Gina R. Boswell'),
('Electronic Arts', 'EA', 'Entertainment', 'Redwood City, California', 'https://ea.com', '13,400', 'Andrew Wilson'),
('Taylor Morrison Home', 'TMHC', 'Homebuilders', 'Scottsdale, Arizona', 'https://taylormorrison.com', '2,800', 'Sheryl D. Palmer'),
('Zimmer Biomet Holdings', 'ZBH', 'Medical Products and Equipment', 'Warsaw, Indiana', 'https://zimmerbiomet.com', '18,000', 'Ivan Tornos'),
('Clorox', 'CLX', 'Household and Personal Products', 'Oakland, California', 'https://thecloroxcompany.com', '8,700', 'Linda Rendle'),
('Xylem', 'XYL', 'Industrial Machinery', 'Washington, District Of Columbia', 'https://xylem.com', '23,000', 'Matthew F. Pine'),
('Voya Financial', 'VOYA', 'Diversified Financials', 'New York, New York', 'https://voya.com', '9,000', 'Heather H. Lavallee'),
('Fastenal', 'FAST', 'Wholesalers: Diversified', 'Winona, Minnesota', 'https://fastenal.com', '20,721', 'Daniel L. Florness'),
('Watsco', 'WSO', 'Wholesalers: Diversified', 'Miami, Florida', 'https://watsco.com', '7,388', 'Albert H. Nahmad'),
('Workday', 'WDAY', 'Computer Software', 'Pleasanton, California', 'https://workday.com', '18,800', 'Carl M. Eschenbach'),
('Old Republic International', 'ORI', 'Insurance: Property and Casualty (Stock)', 'Chicago, Illinois', 'https://oldrepublic.com', '9,200', 'Craig R. Smiddy'),
('RPM International', 'RPM', 'Chemicals', 'Medina, Ohio', 'https://rpminc.com', '17,274', 'Frank C. Sullivan'),
('UFP Industries', 'UFPI', 'Building Materials, Glass', 'Grand Rapids, Michigan', 'https://ufpi.com', '15,800', 'Matthew J. Missad'),
('Ameren', 'AEE', 'Utilities: Gas and Electric', 'St. Louis, Missouri', 'https://ameren.com', '9,372', 'Martin J. Lyons Jr.'),
('Knight-Swift Transportation Hldgs.', 'KNX', 'Trucking, Truck Leasing', 'Phoenix, Arizona', 'https://investor.knight-swift.com', '34,550', 'Adam W. Miller'),
('Monster Beverage', 'MNST', 'Beverages', 'Corona, California', 'https://monsterbevcorp.com', '5,629', 'Rodney C. Sacks'),
('Intuitive Surgical', 'ISRG', 'Medical Products and Equipment', 'Sunnyvale, California', 'https://intuitive.com', '13,676', 'Gary S. Guthart'),
('Super Micro Computer', 'SMCI', 'Computers, Office Equipment', 'San Jose, California', 'https://supermicro.com', '5,126', 'Charles Liang'),
('Concentrix', 'CNXC', 'Information Technology Services', 'Newark, California', 'https://concentrix.com', '440,000', 'Christopher A. Caldwell'),
('O-I Glass', 'OI', 'Packaging, Containers', 'Perrysburg, Ohio', 'https://o-i.com', '23,000', 'Gordon J. Hardie');
